[config]
schemaVersion = "0.0.1"


[package]
namespace = "zannc"
name = "GodsAPI"
versionNumber = "1.0.1"
description = "A library for developers to easily add new Gods / NPC Gods to the game without having to dig through files."
websiteUrl = "https://github.com/excellent-ae/zannc-GodsAPI"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.70"
SGG_Modding-ModUtil = "4.0.1"
LuaENVY-ENVY = "1.2.0"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.2"
SGG_Modding-SJSON = "1.0.0"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"

[publish]
repository = "https://thunderstore.io"
communities = ["hades-ii"]

[publish.categories]
hades-ii = ["mods", "tools", "libraries"]
